#!/usr/bin/env bash

echo "Update Android SDK version from v$1 to v$2 in gradle.properties and README files"

if [ -z "$1" ]; then
  echo "Old version not supplied as the first argument"
  exit 1
elif [ -z "$2" ]; then
  echo "New version not supplied as the second argument"
  exit 1
fi

sed -i '' "s/$1/$2/g" gradle.properties README.md README-CN.md library-notifications/README.md library-notifications/README-CN.md

echo "---------------------------------------------------------------------"
echo "Have you updated the CHANGELOG.md with changes in v$2 ?"
echo "---------------------------------------------------------------------"