name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches: [ github_action_integration ]
  pull_request:
    branches: [ github_action_integration ]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish package
        run: gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
